image:
  registry: docker.io
  repository: grafana/promtail
  tag: 2.9.8
sidecar:
  configReloader:
    image:
      registry: ghcr.io
      repository: jimmidyson/configmap-reload
      tag: v0.13.0
